// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gactus.proto

package gactus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Constant_ContentType int32

const (
	Constant_CONTENT_TYPE_NULL                  Constant_ContentType = 0
	Constant_CONTENT_TYPE_JSON                  Constant_ContentType = 1
	Constant_CONTENT_TYPE_FORM_DATA             Constant_ContentType = 2
	Constant_CONTENT_TYPE_X_WWW_FORM_URLENCODED Constant_ContentType = 3
)

var Constant_ContentType_name = map[int32]string{
	0: "CONTENT_TYPE_NULL",
	1: "CONTENT_TYPE_JSON",
	2: "CONTENT_TYPE_FORM_DATA",
	3: "CONTENT_TYPE_X_WWW_FORM_URLENCODED",
}
var Constant_ContentType_value = map[string]int32{
	"CONTENT_TYPE_NULL":                  0,
	"CONTENT_TYPE_JSON":                  1,
	"CONTENT_TYPE_FORM_DATA":             2,
	"CONTENT_TYPE_X_WWW_FORM_URLENCODED": 3,
}

func (x Constant_ContentType) String() string {
	return proto.EnumName(Constant_ContentType_name, int32(x))
}
func (Constant_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gactus_ab08f580e8bbfe96, []int{0, 0}
}

type Constant struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Constant) Reset()         { *m = Constant{} }
func (m *Constant) String() string { return proto.CompactTextString(m) }
func (*Constant) ProtoMessage()    {}
func (*Constant) Descriptor() ([]byte, []int) {
	return fileDescriptor_gactus_ab08f580e8bbfe96, []int{0}
}
func (m *Constant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Constant.Unmarshal(m, b)
}
func (m *Constant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Constant.Marshal(b, m, deterministic)
}
func (dst *Constant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Constant.Merge(dst, src)
}
func (m *Constant) XXX_Size() int {
	return xxx_messageInfo_Constant.Size(m)
}
func (m *Constant) XXX_DiscardUnknown() {
	xxx_messageInfo_Constant.DiscardUnknown(m)
}

var xxx_messageInfo_Constant proto.InternalMessageInfo

type Request struct {
	Command              string               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	LogId                string               `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ContentType          Constant_ContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=gactus.Constant_ContentType" json:"content_type,omitempty"`
	Body                 []byte               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	IsProto              bool                 `protobuf:"varint,5,opt,name=is_proto,json=isProto,proto3" json:"is_proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_gactus_ab08f580e8bbfe96, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Request) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *Request) GetContentType() Constant_ContentType {
	if m != nil {
		return m.ContentType
	}
	return Constant_CONTENT_TYPE_NULL
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetIsProto() bool {
	if m != nil {
		return m.IsProto
	}
	return false
}

type Response struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_gactus_ab08f580e8bbfe96, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Constant)(nil), "gactus.Constant")
	proto.RegisterType((*Request)(nil), "gactus.Request")
	proto.RegisterType((*Response)(nil), "gactus.Response")
	proto.RegisterEnum("gactus.Constant_ContentType", Constant_ContentType_name, Constant_ContentType_value)
}

func init() { proto.RegisterFile("gactus.proto", fileDescriptor_gactus_ab08f580e8bbfe96) }

var fileDescriptor_gactus_ab08f580e8bbfe96 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0xe9, 0xdf, 0x7c, 0xb7, 0x45, 0xe2, 0x40, 0x65, 0x14, 0x91, 0x90, 0x85, 0x64,
	0x95, 0x85, 0x3e, 0x80, 0x94, 0x24, 0x82, 0x12, 0x93, 0x32, 0xa6, 0x44, 0x57, 0x43, 0x9a, 0x0c,
	0x21, 0xd0, 0xce, 0x44, 0x67, 0xba, 0xc8, 0xca, 0x07, 0xf0, 0x4d, 0x7c, 0x4a, 0x31, 0xb1, 0xb4,
	0xc5, 0xdd, 0x3d, 0xe7, 0xdc, 0x03, 0xf7, 0x77, 0x61, 0x5a, 0x66, 0xb9, 0xde, 0x2a, 0xb7, 0x7e,
	0x97, 0x5a, 0xe2, 0x51, 0xa7, 0xec, 0x4f, 0x04, 0x86, 0x27, 0x85, 0xd2, 0x99, 0xd0, 0xf6, 0x07,
	0x4c, 0x3c, 0x29, 0x34, 0x17, 0x3a, 0x69, 0x6a, 0x8e, 0x67, 0x70, 0xea, 0xc5, 0x51, 0x12, 0x44,
	0x09, 0x4b, 0x5e, 0x17, 0x01, 0x8b, 0x96, 0x61, 0x68, 0xfe, 0xfb, 0x63, 0x3f, 0x3e, 0xc7, 0x91,
	0x89, 0xf0, 0x05, 0x9c, 0x1d, 0xd9, 0xf7, 0x31, 0x7d, 0x62, 0xfe, 0x3c, 0x99, 0x9b, 0x3d, 0x7c,
	0x0d, 0xf6, 0x51, 0xf6, 0xc2, 0xd2, 0x34, 0xed, 0x36, 0x96, 0x34, 0x0c, 0x22, 0x2f, 0xf6, 0x03,
	0xdf, 0xec, 0xdb, 0x5f, 0x08, 0xc6, 0x94, 0xbf, 0x6d, 0xb9, 0xd2, 0x98, 0xc0, 0x38, 0x97, 0x9b,
	0x4d, 0x26, 0x0a, 0x82, 0x2c, 0xe4, 0xfc, 0xa7, 0x3b, 0x89, 0x67, 0x30, 0x5a, 0xcb, 0x92, 0x55,
	0x05, 0xe9, 0xb5, 0xc1, 0x70, 0x2d, 0xcb, 0x87, 0x02, 0xdf, 0xc1, 0x34, 0xef, 0xae, 0x67, 0xba,
	0xa9, 0x39, 0xe9, 0x5b, 0xc8, 0x39, 0xb9, 0xb9, 0x74, 0x7f, 0xb9, 0x77, 0x94, 0xee, 0x01, 0x22,
	0x9d, 0xe4, 0x07, 0xbc, 0x18, 0x06, 0x2b, 0x59, 0x34, 0x64, 0x60, 0x21, 0x67, 0x4a, 0xdb, 0x19,
	0x9f, 0x83, 0x51, 0x29, 0xd6, 0xfe, 0x8c, 0x0c, 0x2d, 0xe4, 0x18, 0x74, 0x5c, 0xa9, 0xc5, 0x8f,
	0xb4, 0xaf, 0xc0, 0xa0, 0x5c, 0xd5, 0x52, 0xa8, 0x7d, 0x15, 0xed, 0xab, 0xab, 0x51, 0xdb, 0xba,
	0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x98, 0xea, 0x03, 0x79, 0x01, 0x00, 0x00,
}
