// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gactus.proto

package gactus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Constant_ContentType int32

const (
	Constant_CONTENT_TYPE_NULL                  Constant_ContentType = 0
	Constant_CONTENT_TYPE_JSON                  Constant_ContentType = 1
	Constant_CONTENT_TYPE_FORM_DATA             Constant_ContentType = 2
	Constant_CONTENT_TYPE_X_WWW_FORM_URLENCODED Constant_ContentType = 3
)

var Constant_ContentType_name = map[int32]string{
	0: "CONTENT_TYPE_NULL",
	1: "CONTENT_TYPE_JSON",
	2: "CONTENT_TYPE_FORM_DATA",
	3: "CONTENT_TYPE_X_WWW_FORM_URLENCODED",
}
var Constant_ContentType_value = map[string]int32{
	"CONTENT_TYPE_NULL":                  0,
	"CONTENT_TYPE_JSON":                  1,
	"CONTENT_TYPE_FORM_DATA":             2,
	"CONTENT_TYPE_X_WWW_FORM_URLENCODED": 3,
}

func (x Constant_ContentType) String() string {
	return proto.EnumName(Constant_ContentType_name, int32(x))
}
func (Constant_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gactus_d87872074af2bf12, []int{0, 0}
}

type Constant_HttpMethod int32

const (
	Constant_HTTP_METHOD_NULL Constant_HttpMethod = 0
	Constant_HTTP_METHOD_GET  Constant_HttpMethod = 1
	Constant_HTTP_METHOD_POST Constant_HttpMethod = 2
)

var Constant_HttpMethod_name = map[int32]string{
	0: "HTTP_METHOD_NULL",
	1: "HTTP_METHOD_GET",
	2: "HTTP_METHOD_POST",
}
var Constant_HttpMethod_value = map[string]int32{
	"HTTP_METHOD_NULL": 0,
	"HTTP_METHOD_GET":  1,
	"HTTP_METHOD_POST": 2,
}

func (x Constant_HttpMethod) String() string {
	return proto.EnumName(Constant_HttpMethod_name, int32(x))
}
func (Constant_HttpMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gactus_d87872074af2bf12, []int{0, 1}
}

type Constant struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Constant) Reset()         { *m = Constant{} }
func (m *Constant) String() string { return proto.CompactTextString(m) }
func (*Constant) ProtoMessage()    {}
func (*Constant) Descriptor() ([]byte, []int) {
	return fileDescriptor_gactus_d87872074af2bf12, []int{0}
}
func (m *Constant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Constant.Unmarshal(m, b)
}
func (m *Constant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Constant.Marshal(b, m, deterministic)
}
func (dst *Constant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Constant.Merge(dst, src)
}
func (m *Constant) XXX_Size() int {
	return xxx_messageInfo_Constant.Size(m)
}
func (m *Constant) XXX_DiscardUnknown() {
	xxx_messageInfo_Constant.DiscardUnknown(m)
}

var xxx_messageInfo_Constant proto.InternalMessageInfo

type Request struct {
	Command              string               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	LogId                string               `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ContentType          Constant_ContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=gactus.Constant_ContentType" json:"content_type,omitempty"`
	Body                 []byte               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	IsProto              bool                 `protobuf:"varint,5,opt,name=is_proto,json=isProto,proto3" json:"is_proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_gactus_d87872074af2bf12, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Request) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *Request) GetContentType() Constant_ContentType {
	if m != nil {
		return m.ContentType
	}
	return Constant_CONTENT_TYPE_NULL
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetIsProto() bool {
	if m != nil {
		return m.IsProto
	}
	return false
}

type HttpConfig struct {
	Method               Constant_HttpMethod `protobuf:"varint,1,opt,name=method,proto3,enum=gactus.Constant_HttpMethod" json:"method,omitempty"`
	Path                 string              `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HttpConfig) Reset()         { *m = HttpConfig{} }
func (m *HttpConfig) String() string { return proto.CompactTextString(m) }
func (*HttpConfig) ProtoMessage()    {}
func (*HttpConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_gactus_d87872074af2bf12, []int{2}
}
func (m *HttpConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpConfig.Unmarshal(m, b)
}
func (m *HttpConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpConfig.Marshal(b, m, deterministic)
}
func (dst *HttpConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpConfig.Merge(dst, src)
}
func (m *HttpConfig) XXX_Size() int {
	return xxx_messageInfo_HttpConfig.Size(m)
}
func (m *HttpConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HttpConfig proto.InternalMessageInfo

func (m *HttpConfig) GetMethod() Constant_HttpMethod {
	if m != nil {
		return m.Method
	}
	return Constant_HTTP_METHOD_NULL
}

func (m *HttpConfig) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*Constant)(nil), "gactus.Constant")
	proto.RegisterType((*Request)(nil), "gactus.Request")
	proto.RegisterType((*HttpConfig)(nil), "gactus.HttpConfig")
	proto.RegisterEnum("gactus.Constant_ContentType", Constant_ContentType_name, Constant_ContentType_value)
	proto.RegisterEnum("gactus.Constant_HttpMethod", Constant_HttpMethod_name, Constant_HttpMethod_value)
}

func init() { proto.RegisterFile("proto/gactus.proto", fileDescriptor_gactus_d87872074af2bf12) }

var fileDescriptor_gactus_d87872074af2bf12 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x6e, 0xda, 0x40,
	0x14, 0x85, 0x3b, 0xfc, 0x18, 0x7a, 0x41, 0xd4, 0x9d, 0x96, 0xca, 0xfd, 0x59, 0x58, 0x5e, 0x54,
	0x5e, 0x51, 0x09, 0x1e, 0xa0, 0x42, 0xb6, 0x13, 0x12, 0xe1, 0x1f, 0x0d, 0x83, 0x48, 0x56, 0x23,
	0x63, 0x3b, 0xc6, 0x12, 0x78, 0x9c, 0x78, 0x58, 0xb0, 0xca, 0xfb, 0xe4, 0x91, 0xf2, 0x34, 0x11,
	0x63, 0x50, 0x20, 0xec, 0xee, 0x39, 0xf7, 0x48, 0x67, 0xee, 0x37, 0x80, 0x8b, 0x27, 0x2e, 0xf8,
	0xbf, 0x34, 0x8c, 0xc4, 0xb6, 0x1c, 0x48, 0x81, 0x95, 0x4a, 0x19, 0xaf, 0x08, 0xda, 0x16, 0xcf,
	0x4b, 0x11, 0xe6, 0xc2, 0x78, 0x86, 0x8e, 0xc5, 0x73, 0x91, 0xe4, 0x82, 0xee, 0x8a, 0x04, 0xf7,
	0xe1, 0xab, 0xe5, 0x7b, 0xd4, 0xf1, 0x28, 0xa3, 0xf7, 0x81, 0xc3, 0xbc, 0xf9, 0x74, 0xaa, 0x7e,
	0xba, 0xb0, 0x6f, 0x67, 0xbe, 0xa7, 0x22, 0xfc, 0x0b, 0x7e, 0x9c, 0xd9, 0x57, 0x3e, 0x71, 0x99,
	0x3d, 0xa6, 0x63, 0xb5, 0x86, 0xff, 0x82, 0x71, 0xb6, 0xbb, 0x63, 0x8b, 0xc5, 0xa2, 0x4a, 0xcc,
	0xc9, 0xd4, 0xf1, 0x2c, 0xdf, 0x76, 0x6c, 0xb5, 0x6e, 0xb8, 0x00, 0x13, 0x21, 0x0a, 0x37, 0x11,
	0x2b, 0x1e, 0xe3, 0xef, 0xa0, 0x4e, 0x28, 0x0d, 0x98, 0xeb, 0xd0, 0x89, 0x6f, 0x1f, 0xeb, 0xbf,
	0xc1, 0x97, 0x53, 0xf7, 0xda, 0xa1, 0x2a, 0xfa, 0x18, 0x0d, 0xfc, 0x19, 0x55, 0x6b, 0xc6, 0x0b,
	0x82, 0x16, 0x49, 0x1e, 0xb7, 0x49, 0x29, 0xb0, 0x06, 0xad, 0x88, 0x6f, 0x36, 0x61, 0x1e, 0x6b,
	0x48, 0x47, 0xe6, 0x67, 0x72, 0x94, 0xb8, 0x0f, 0xca, 0x9a, 0xa7, 0x2c, 0x8b, 0xb5, 0x9a, 0x5c,
	0x34, 0xd7, 0x3c, 0xbd, 0x89, 0xf1, 0x7f, 0xe8, 0x46, 0x15, 0x0c, 0x26, 0x76, 0x45, 0xa2, 0xd5,
	0x75, 0x64, 0xf6, 0x86, 0x7f, 0x06, 0x07, 0x8c, 0x47, 0x68, 0x83, 0x13, 0x62, 0xa4, 0x13, 0x9d,
	0xe0, 0xc3, 0xd0, 0x58, 0xf2, 0x78, 0xa7, 0x35, 0x74, 0x64, 0x76, 0x89, 0x9c, 0xf1, 0x4f, 0x68,
	0x67, 0x25, 0x93, 0x5f, 0xa0, 0x35, 0x75, 0x64, 0xb6, 0x49, 0x2b, 0x2b, 0x83, 0xbd, 0x34, 0xe6,
	0xd5, 0xed, 0x16, 0xcf, 0x1f, 0xb2, 0x14, 0x8f, 0x40, 0xd9, 0x48, 0x0a, 0xf2, 0xb5, 0xbd, 0xe1,
	0xef, 0x8b, 0xde, 0x77, 0x50, 0xe4, 0x10, 0xdd, 0x37, 0x16, 0xa1, 0x58, 0x1d, 0xee, 0x90, 0xf3,
	0x52, 0x91, 0x65, 0xa3, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0xec, 0xe6, 0xa3, 0x05, 0x02,
	0x00, 0x00,
}
